#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
read -rp "User: " -e user
read -rp "Key: " -e key
read -rp "Expired (days): " -e masaaktif
exp_d=`date -d "$masaaktif days" +"%Y-%m-%d"`
exp_h=`date +"%T"`
sed -i '/#trojanws$/a\### '"$user $exp_d $exp_h"'\
},{"password": "'""$key""'","email": "'""$user""'"' /etc/xray/trojan.json
sed -i '/#trojangrpc$/a\### '"$user $exp_d $exp_h"'\
},{"password": "'""$key""'","email": "'""$user""'"' /etc/xray/trojan-grpc.json
systemctl restart xray
systemctl restart xray@trojan
systemctl restart xray@trojan-grpc