#!/bin/bash
data=( `cat /etc/xray/trojan.json | grep '^###' | cut -d ' ' -f 2`);
now_d=`date +"%Y-%m-%d"`
now_h=`date +"%T"`
for user in "${data[@]}"
do
exp_d=$(grep -w "^### $user" "/etc/xray/trojan.json" | cut -d ' ' -f 3)
exp_h=$(grep -w "^### $user" "/etc/xray/trojan.json" | cut -d ' ' -f 4)
d1=$(date -d "$exp_d" +%s)
d2=$(date -d "$exp_h" +%s)
d3=$(date -d "$now_d" +%s)
d4=$(date -d "$now_h" +%s)
exp1=$(( (d1 - d3) / 86400 ))
exp2=$(( (d2 - d4) / 60 ))
if [[ "$exp1" == "0" && "$exp2" == "0" ]]; then
sed -i "/^### $user $exp_d $exp_h/,/^},{/d" /etc/xray/trojan.json
sed -i "/^### $user $exp_d $exp_h/,/^},{/d" /etc/xray/trojan-grpc.json
systemctl restart xray@trojan
systemctl restart xray@trojan-grpc
fi
done
data=( `cat /etc/xray/vmess.json | grep '^###' | cut -d ' ' -f 2`);
now_d=`date +"%Y-%m-%d"`
now_h=`date +"%T"`
for user in "${data[@]}"
do
exp_d=$(grep -w "^### $user" "/etc/xray/vmess.json" | cut -d ' ' -f 3)
exp_h=$(grep -w "^### $user" "/etc/xray/vmess.json" | cut -d ' ' -f 4)
d1=$(date -d "$exp_d" +%s)
d2=$(date -d "$exp_h" +%s)
d3=$(date -d "$now_d" +%s)
d4=$(date -d "$now_h" +%s)
exp1=$(( (d1 - d3) / 86400 ))
exp2=$(( (d2 - d4) / 60 ))
if [[ "$exp1" == "0" && "$exp2" == "0" ]]; then
sed -i "/^### $user $exp_d $exp_h/,/^},{/d" /etc/xray/vmess.json
sed -i "/^### $user $exp_d $exp_h/,/^},{/d" /etc/xray/vmess-grpc.json
systemctl restart xray@vmess
systemctl restart xray@vmess-grpc
fi
done